### ISSUE TITLE
Confirmable messages sending

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [ARMmbed/mbed-client-c#70] opened 2016-07-28 12:23 UTC
Hi there,

I observed that if I try to send more confirmable CoAP messages that "linked_list_resent_msgs" is able to hold (by default is set to 2 in the following using this [define](https://github.com/ARMmbed/mbed-client-c/blob/master/source/libCoap/src/include/sn_coap_protocol_internal.h#L43)) The messages obviously do not get stored into the list, but are send out anyway.

Which means that if the delivery fails the device will not retry to send those packages anymore.

Is that the intended behaviour?

**Comment by ciarmcom** [comment] 2016-08-01 12:50
ARM Internal Ref: IOTCLT-882

**Comment by anttiylitokola** [comment] 2016-08-02 09:47
Hi, yes that is the intended behavior. 
What we can do is to add new build time parameter for controlling SN_COAP_RESENDING_QUEUE_SIZE_MSGS flag, do you see any use for that?

**Comment by javier-moreno-tridonic-com** [comment] 2016-08-02 10:01
I think it is useful to control how much memory will be spent on the list. Also could be interesting for us to increase the amount of "tracked" CoAP messages (currently we increased that value manually)

**Comment by anttiylitokola** [comment] 2016-11-03 13:37
Hi, changes are done through https://github.com/ARMmbed/mbed-client-c/pull/78 and merged to master. I'll close this ticket now.

**Closed by anttiylitokola** 2016-11-03 13:37 UTC
Labels: mirrored
